default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <% if ENV["DATABASE_URL"].present? %>
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  <% else %>
  adapter: sqlite3
  database: storage/production.sqlite3
  timeout: 5000
  <% end %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
